### ISSUE TITLE
 Mobile Meta tag

### ISSUE THREAD

**Issue by Mikeysax** [jetcitycoder/inconceivableqm#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by cpplain** [comment]
Thanks for the suggestion. I've added the following meta tag:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Everything renders well on my mobile test device (iPhone 6S, iOS 10.2).
